### ISSUE TITLE
Wrong rendering order (Itäväylä, Muuntajankatu, Helsinki)

### ISSUE THREAD

**Issue by jnumm** [HSLdevcom/hsl-map-style#40]
The trunk_link roads [6268476](https://www.openstreetmap.org/way/6268476) and [4868193](https://www.openstreetmap.org/way/4868193) are shown under [54200876](https://www.openstreetmap.org/way/54200876); they should be above instead.

[Link to OSM](https://www.openstreetmap.org/#map=19/60.20582/25.04627)
[Link to Reittiopas](https://www.reittiopas.fi/Siilitie%202a%2C%20Helsinki%3A%3A60.20599822657623%2C25.04594743251801/-/lahellasi?time=1535870641)

![reittiopas](https://user-images.githubusercontent.com/1366407/44952958-a1569900-ae94-11e8-852c-64b2326b27ff.png)
![standard](https://user-images.githubusercontent.com/1366407/44952961-a74c7a00-ae94-11e8-8e75-76c40a0ec411.png)
![cyclemap](https://user-images.githubusercontent.com/1366407/44952962-aae00100-ae94-11e8-8aa1-46e3c0551f94.png)
![humanitarian](https://user-images.githubusercontent.com/1366407/44952963-ad425b00-ae94-11e8-8748-522ca8d75188.png)

**Comment by houtari** [comment]
I created an issue out of this into our project backlog.

**Comment by varpushaukka** [comment]
this was fixed in #41
